### ISSUE TITLE
Error when trying to submit job

### ISSUE THREAD

**Issue by darylteo** [aws-solutions/video-on-demand-on-aws-foundations#24]
**Describe the bug**

```
2022-10-10T05:29:05.307Z	4cc35dea-e300-4ec3-9008-40971534614c	ERROR	Invoke Error 	
{
    "errorType": "UnexpectedParameter",
    "errorMessage": "Unexpected key 'Name' found in params",
    "code": "UnexpectedParameter",
    "message": "Unexpected key 'Name' found in params",
    "time": "2022-10-10T05:29:04.809Z",
    "stack": [
        "UnexpectedParameter: Unexpected key 'Name' found in params",
        "    at ParamValidator.fail (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:50:37)",
        "    at ParamValidator.validateStructure (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:77:14)",
        "    at ParamValidator.validateMember (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:88:21)",
        "    at ParamValidator.validate (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:34:10)",
        "    at Request.VALIDATE_PARAMETERS (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:132:42)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:96:12)",
        "    at /var/runtime/node_modules/aws-sdk/lib/event_listeners.js:86:9",
        "    at finish (/var/runtime/node_modules/aws-sdk/lib/config.js:396:7)",
        "    at /var/runtime/node_modules/aws-sdk/lib/config.js:414:9"
    ]
}
```

**To Reproduce**

 - spin up CF stack
 - upload this Job Settings file (unsure if any impact)

[job-settings.txt](https://github.com/aws-solutions/video-on-demand-on-aws-foundations/files/9743559/job-settings.txt)

 - upload a mov to source-bucket/assets01/
 - no file created, no job submitted, stack trace above

**Expected behavior**

Job is submitted and video files created

**Please complete the following information about the solution:**
- [1.1.0 ] Version: [e.g. v1.0.0]
- [ap-southeast-2] Region: [e.g. us-east-1]
- [Yes] Was the solution modified from the version published on this repository?
- [Yes] If the answer to the previous question was yes, are the changes available on GitHub?
- [Yes] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [Yes] Were there any errors in the CloudWatch Logs?

**Additional context**
Not sure if there was any API changes recently that might have broken the default source code. Any help appreciated.

**Comment by darylteo** [comment]
Aha found the issue. 

The Job Template that I created using the MediaConvert management console requires one you put in a Template Name.

Exporting it from the Management Console exports it with a "Name" property, and the SDK doesn't like it for some reason (maybe an old version within the zip file in the template?).

**Comment by cassneal** [comment]
Hi @darylteo we have added this issue to our solution's backlog. Thank you for filing. Feel free to add any more comments if you find out any more details.
